version: "2"

services:
  dolibarr:
    #image: dolibarr/docker-dolibarr:apache
    build: ./
    container_name: dolibarr
    restart: always
    depends_on:
      - dolibarrdb
    links:
      - dolibarrdb
    ports:
      - 80:80
    volumes:
      - /srv/dolibarr/html:/var/www/html
      - /srv/dolibarr/documents:/var/www/documents
      - /srv/dolibarr/scripts:/var/www/scripts
    environment:
      - DOLI_AUTO_CONFIGURE=1
      - DOLI_AUTO_INSTALL=1
      - DOLI_ADMIN_LOGIN=admin
      - DOLI_ADMIN_PWD=somethingrandomandsecure
      - DOLI_DB_HOST=dolibarrdb # same as mysql container name
      - DOLI_DB_NAME=dolibarr # same as mysql MYSQL_DATABASE env name
      - DOLI_DB_USER=dolibarr # same as mysql MYSQL_USER env name
      - DOLI_DB_PASSWORD=dolibarrdbpass # same as mysql MYSQL_PASSWORD env name

  dolibarrdb:
    image: mariadb:latest
    container_name: dolibarrdb
    restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    ports:
      - 3306:3306
    volumes:
      - /srv/dolibarr/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=dolibarr
      - MYSQL_USER=dolibarr
      - MYSQL_PASSWORD=dolibarrdbpass
